services:
  backend:
    build: ./backend
    ports: 
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://admin:password@mongo:27017/ddf_db?authSource=admin
      - SECRET_KEY=TestSecretKey
    network_mode: host
  mongo:
    image: mongo:latest
    ports: 
      - "27017:27017"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=password
    volumes: 
      - mongo_data:/data/db
    network_mode: host

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    network_mode: host

volumes: 
  mongo_data: