services:
  backend:
    build: ./backend
    depends_on:
      - mongo
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ddf.rule=Host(`api.derduemmstefliegt.online`)"
      - "traefik.http.routers.ddf.entrypoints=websecure"
      - "traefik.http.services.ddf.loadbalancer.server.port=8000"
    environment:
      - MONGODB_URL=mongodb://admin:password@mongo:27017/ddf_db?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USER=default
      - REDIS_PASSWORD=changeme
      - REDIS_DB=0
      - SECRET_KEY=TestSecretKey
    networks:
      - ddf

  mongo:
    image: mongo:latest
    labels:
      - "traefik.enable=false"
    ports:
      - "27017:27017"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db
    networks:
      - ddf

  redis:
    image: redis:latest
    labels:
      - "traefik.enable=false"
    command: ["redis-server", "--requirepass", "changeme"]
    ports:
      - "6379:6379"
    networks:
      - ddf
    volumes:
      - redis_data:/data

  frontend:
    build: ./frontend
    depends_on:
      - backend
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ddf.rule=Host(`derduemmstefliegt.online`)"
        - "traefik.http.routers.ddf.entrypoints=web"
        - "traefik.http.services.ddf.loadbalancer.server.port=80"
    networks:
      - ddf

volumes:
  mongo_data:
  redis_data:

networks:
  ddf:
    external: true