services:
  backend:
    build: ./backend
    ports: 
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://admin:password@mongo:27017/ddf_db?authSource=admin
      - SECRET_KEY=TestSecretKey
    networks:
        - ddf_network
  mongo:
    image: mongo:latest
    ports: 
      - "27017:27017"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=password
    volumes: 
      - mongo_data:/data/db
    networks:
        - ddf_network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - ddf_network

volumes: 
  mongo_data:

networks:
  ddf_network:
    driver: bridge