name: Deploy to Test Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup SSH for server
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup SSH for GitHub
        run: |
          echo "${{ secrets.GH_SSH_KEY }}" > ~/.ssh/actions_ssh
          chmod 600 ~/.ssh/actions_ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          got config --global core.sshCommand "ssh -i ~/.ssh/actions_ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

      - name: Deploy to Test Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 root@45.138.49.163 "cd /home/ddf && docker-compose down && git stash && git config pull.rebase false && git pull origin dev && docker-compose up --build -d"

