name: Deploy to Test Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Test Server
        run: |
          ssh -o StrictHostKeyChecking=no root@45.138.49.163 "cd /home/ddf && docker-compose down && git stash && git pull origin dev && docker-compose up -d"